# This workflow will ensure the code coverage of all unit tests meets a minimum standard.

name: coverage

on:
  push:
    branches: [ "main", "dev", "feature/5-coverage-workflow" ] 
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Check coverage
      run: |
        pytest tests/menelaus --cov=src/ --cov-report term
        coverage report -m --fail-under=100